#ifndef JZ2440_UI_LAYOUT_H
#define JZ2440_UI_LAYOUT_H

/* Single-page 480x272 dashboard layout. Keep all UI geometry here. */
#define SCREEN_W 480
#define SCREEN_H 272
#define HEADER_H 44

#define TITLE_X 20
#define TITLE_Y 9
#define TITLE_SCALE 2
#define TITLE_SPACING 2
#define HEADER_STATUS_X 278
#define HEADER_STATUS_Y 18
#define HEADER_CLOCK_X 394
#define HEADER_CLOCK_Y 18
#define HEADER_TEXT_SCALE 1
#define HEADER_TEXT_SPACING 1

#define CARD_Y 52
#define CARD_W 216
#define CARD_H 150
#define LEFT_CARD_X 16
#define RIGHT_CARD_X 248
#define CARD_LABEL_X_INSET 12
#define CARD_LABEL_Y 66
#define CARD_PERCENT_Y 87
#define CARD_PERCENT_SCALE 3
#define CARD_PERCENT_SPACING 3
#define CARD_BAR_X_INSET 16
#define CARD_BAR_Y 121
#define CARD_BAR_W 184
#define CARD_BAR_H 16
#define CARD_RESET_Y 146
#define CARD_RESET_VALUE_Y 162
#define CARD_TEXT_SPACING 2

#define WAITING_X 166
#define WAITING_Y 206
#define WAITING_SCALE 1
#define WAITING_SPACING 1

#define FOOTER_X 16
#define FOOTER_Y 220
#define FOOTER_W 448
#define FOOTER_H 32
#define FOOTER_TEXT_X 30
#define FOOTER_VALUE_X 128
#define FOOTER_TEXT_Y 232
#define FOOTER_TEXT_SPACING 1

#define COLOR_BG_R 0
#define COLOR_BG_G 0
#define COLOR_BG_B 0
#define COLOR_TEXT_R 205
#define COLOR_TEXT_G 220
#define COLOR_TEXT_B 235
#define COLOR_LABEL_R 165
#define COLOR_LABEL_G 180
#define COLOR_LABEL_B 195
#define COLOR_MUTED_R 120
#define COLOR_MUTED_G 135
#define COLOR_MUTED_B 150
#define COLOR_GREEN_R 50
#define COLOR_GREEN_G 205
#define COLOR_GREEN_B 100
#define COLOR_BLUE_R 65
#define COLOR_BLUE_G 145
#define COLOR_BLUE_B 235
#define COLOR_WARNING_R 235
#define COLOR_WARNING_G 205
#define COLOR_WARNING_B 50
#define COLOR_ERROR_R 235
#define COLOR_ERROR_G 65
#define COLOR_ERROR_B 65
#define COLOR_BORDER_R 100
#define COLOR_BORDER_G 120
#define COLOR_BORDER_B 140
#define COLOR_FOOTER_R 20
#define COLOR_FOOTER_G 30
#define COLOR_FOOTER_B 45

#endif
